### ISSUE TITLE
non-zero exit codes from child processes are ignored

### ISSUE THREAD

**Issue by majewsky** [flonatel/pipexec#11] opened 2016-08-30 16:07 UTC
A normal shell pipe will have an exit code equal to the exit code of the last process in the chain. Also, the option `set -o pipefail` will cause a pipe to propagate a non-zero exit code from any process in the chain. pipexec, however, seems to ignore the exit codes of its child processes:

``` bash
$ pipexec -- [ A /bin/true ] [ B /bin/true ] "{A:1>B:0}" "{B:1>A:0}"; echo $?
0
$ pipexec -- [ A /bin/false ] [ B /bin/true ] "{A:1>B:0}" "{B:1>A:0}"; echo $?
0
$ pipexec -- [ A /bin/false ] [ B /bin/false ] "{A:1>B:0}" "{B:1>A:0}"; echo $?
0
```

I would like at least an option to make pipexec behave like a normal shell with `set -o pipefail` in this respect.

**Comment by jirutka** [comment] 2017-12-01 01:18
This is really critical flaw. :(

**Comment by flonatel** [comment] 2018-03-18 08:14
In a 'normal' shell script there is a 'natural' order of commands in a pipe: A | B.
What do you think is a 'last' command in a directed graph?

**Comment by rain-1** [comment] 2018-03-18 14:22
related https://github.com/flonatel/pipexec/issues/15

**Comment by jirutka** [comment] 2018-03-18 14:22
That indeed a tricky question and I understand where you’re heading, but the point is that exiting with zero status (i.e. everything is okay) when some of the processes in the chain failed is clearly wrong (errors are silently ignored) and makes this tool unusable for many scenarios. The easiest solution that is not perfect, but should work for most typical use cases, is to add an option to immediately exit with status **S** when _any_ of the processes exit with status **S** where **S** > 0.

**Comment by rain-1** [comment] 2018-03-19 18:16
I agree except don't add 100.

**Comment by flonatel** [comment] 2022-06-18 11:18
For the time being pipexec now returns 1 if one child failed and 0 otherwise.
This is not a 'complete' solution, as it is still not possible to check details of a specific child, but better as returning 0 (everything ok) even if a child fails.

**Comment by flonatel** [comment] 2022-06-20 07:44
The problem is, that there is no way to encode every possible child failure in a single return value.
Therefore I'll stay with: if one child fails, '1' is returned - otherwise 0.

Because pipexec even restarts child processes if they terminate abnormally, there is a need to emit events to get all these information. Therefore I introduced JSON logging (which will make it into the next release).

Every time a child is started or exited, a log is emitted to a fd which can be specified on the command line. Each event consists of a single JSON object. Like:

    $ ./bin/pipexec -j 2 -- '[' A /bin/true ']' '[' B /bin/false ']'
    {"timestamp":1655709797,"pipexec_pid":43500,"id":1,"type":"exec","serverity":"info","message":"New child forked","command":"A","command_pid":"43501"}
    {"timestamp":1655709797,"pipexec_pid":43500,"id":1,"type":"exec","serverity":"info","message":"New child forked","command":"B","command_pid":"43502"}
    {"timestamp":1655709797,"pipexec_pid":43500,"id":2,"type":"exec","serverity":"info","message":"child exit","command_pid":"43501","status":"0","normal_exit":"1","child_status":"0","child_signaled":"0"}
    {"timestamp":1655709797,"pipexec_pid":43500,"id":2,"type":"exec","serverity":"info","message":"child exit","command_pid":"43502","status":"1","normal_exit":"1","child_status":"1","child_signaled":"0"}

A complete documentation about all available fields and their meaning is documented in the man page.

Note: I know that there is a need to match the command and the exit using the PID; the problem is, that the child termination is handled in a signal handler where there is no way to access the command info (e.g. name).

I hope that fixes your problem. Therefore I'll close this issue. If this is not what you need, please make another proposal / reopen it,

**Closed by flonatel** 2022-06-20 07:44 UTC
